version: '3.8'

services:
  dicom-router:
    image: registry.dto.kemkes.go.id/pub/dicom-router:latest
    container_name: dicom-router
    restart: always
    ports:
      - "11113:11112"
      - "8081:8080"
    environment:
      - ORG_ID=100027411
      - CLIENT=A9rCi3e2tr3RDuULjbjUI3IthglbeLV67I9ZGIxZsBdBK8cH
      - SECRET=8k77IYkCcWHAMoAUoPlpRSaJ2aC1EV1WxG9orMG8ZcBY6XjAgHhI6Pp190IGfm1L
      - URL=https://api-satusehat.kemkes.go.id
      - AE_TITLE=DCMROUTER
    volumes:
      - "./out:/app/out"
      - "./logs:/app/logs"
    networks:
      - dicom-net

  dicom-forwarder:
    build: ./forwarder
    container_name: dicom-forwarder
    restart: unless-stopped
    volumes:
      - "./state:/state"
    environment:
      - FTP_HOST=10.5.1.22
      - FTP_PORT=2121
      - FTP_USER=admin
      - FTP_PASS=J4nganM4suk
      - FTP_DIR=/
      - ROUTER_AET=DCMROUTER
      - ROUTER_HOST=dicom-router
      - ROUTER_PORT=11112
      - MAX_RETRIES=3
      - SCAN_INTERVAL=120000
    depends_on:
      - dicom-router
    networks:
      - dicom-net

networks:
  dicom-net:
    driver: bridge