version: '3.8'

services:
  dicom-router:
    image: registry.dto.kemkes.go.id/pub/dicom-router:latest
    container_name: dicom-router-minut
    restart: always
    ports:
      - "11115:11112"
      - "18083:8080"
    environment:
      - PYTHONUNBUFFERED=1
      - ORG_ID=100027411
      - CLIENT=EPF1G1pSX9uwVcf90pgS0L4Gx3WSVGjf0Bo91FqcJKF8sAL7
      - SECRET=y88Wp2JSxDeNRP01BM4GBqWkVZXslXd5lNXR1ytTyk7Iy8jHP2ZFEBGXOs0DJG2P
      - URL=https://api-satusehat.kemkes.go.id
      - AE_TITLE=DCMROUTER
    entrypoint: ["/bin/bash", "-c", "/app/entrypoint.sh 2>&1 | tee -a /app/logs/router.log"]
    volumes:
      - "./out:/app/out"
      - "./logs:/app/logs"
    networks:
      - dicom-net-minut

  dicom-forwarder:
    build: ./forwarder
    container_name: dicom-forwarder-minut
    restart: unless-stopped
    ports:
      - "13003:3000"
    volumes:
      - "./state:/state"
      - "./logs:/router-logs:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    environment:
      - ROUTER_CONTAINER_NAME=dicom-router-minut
      - FTP_HOST=10.5.1.22
      - FTP_PORT=2121
      - FTP_USER=admin
      - FTP_PASS=J4nganM4suk
      - FTP_DIR=/
      - ROUTER_AET=DCMROUTER
      - ROUTER_HOST=dicom-router
      - ROUTER_PORT=11112
      - MAX_RETRIES=3
      - UI_PORT=3000
      - TZ=Asia/Jakarta
      - SCHEDULE_HOUR=2
    depends_on:
      - dicom-router
    networks:
      - dicom-net-minut

networks:
  dicom-net-minut:
    driver: bridge